config/routes.rb
Rails.application.routes.draw do

   resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality:true, inclusion: { in: (0..5), allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :set_restaurant,only:[:show,:edit,:update,:destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
   #@restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
     @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    #@restaurant = Restaurant.find(params[id])
  end

  def update
    #@restaurant = Restaurant.find(params[id])
    @restaurant.update(restaurant_params)
     if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    #@restaurant = Restaurant.find(params[id])
    @restaurant.destroy
    redirect_to restaurant_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
     params.require(:restaurant).permit(:name, :address, :phone_number, :category)
   end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant
  def new
    #@restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new # @restaurant.reviews.build
  end

  def create
    #@restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
     if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
  def review_params
    params.require(:review).permit(:content, :rating)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>

  <%= f.submit "add a restaurant", class: "btn btn-primary" %>
  <% end %>

app/views/restaurants/create.html.erb
<!-- <h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>
 -->

app/views/restaurants/destroy.html.erb
<!-- <h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>
 -->

app/views/restaurants/edit.html.erb
<!-- <h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>
 -->

<%= render 'form' %>

app/views/restaurants/index.html.erb
<!-- <h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p> -->

<% @restaurants.each do |restaurant| %>
  <h3><%= restaurant.name %></h3>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.phone_number %></p>
  <p><%= restaurant.category %></p>

<%= link_to 'Create', new_restaurant_path %>
<%= link_to 'Details', restaurant_path(restaurant) %>
<%= link_to 'Edit', edit_restaurant_path(restaurant) %>
<%= link_to 'Delete', restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
<% end %>

app/views/restaurants/new.html.erb
<!-- <h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>
 -->
<%= render 'form' %>

app/views/restaurants/show.html.erb
<!-- <h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>

 -->
<%= link_to 'Add review', new_restaurant_review_path(@restaurant) %>
<%= link_to "Delete", restaurant_path(@restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } %>


<% @restaurant.reviews.each do |review| %>
<%= review.content %>
<%= review.rating %>
<% end %>

<p><%= @restaurant.name %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>

app/views/restaurants/update.html.erb
<!-- <h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>
 -->

app/views/reviews/create.html.erb
<!-- <h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p> -->

app/views/reviews/new.html.erb
<!-- <h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p> -->


<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>